export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE";



export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";


export const OTP_VERIFY_REQUEST = "OTP_VERIFY_REQUEST";
export const OTP_VERIFY_SUCCESS = "OTP_VERIFY_SUCCESS";
export const OTP_VERIFY_FAILURE = "OTP_VERIFY_FAILURE";

// OTP Request
export const OTP_REQUEST = 'OTP_REQUEST';
export const OTP_REQUEST_SUCCESS = 'OTP_REQUEST_SUCCESS';
export const OTP_REQUEST_FAILURE = 'OTP_REQUEST_FAILURE';

// OTP Verification
export const POST_OTP_VERIFY_REQUEST = 'OTP_VERIFY_REQUEST';
export const POST_OTP_VERIFY_SUCCESS = 'OTP_VERIFY_SUCCESS';
export const POST_OTP_VERIFY_FAILURE = 'OTP_VERIFY_FAILURE';

// Password Reset
export const PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_FAILURE = 'PASSWORD_RESET_FAILURE';