export const GET_LOCATION_REQUEST = "GET_LOCATION_REQUEST";
export const GET_LOCATION_SUCCESS = "GET_LOCATION_SUCCESS";
export const GET_LOCATION_FAILURE = "GET_LOCATION_FAILURE";


export const POST_LOCATION_REQUEST = "POST_LOCATION_REQUEST";
export const POST_LOCATION_SUCCESS = "POST_LOCATION_SUCCESS";
export const POST_LOCATION_FAILURE = "POST_LOCATION_FAILURE";


export const POST_BOOK_SLOT_REQUEST = "POST_BOOK_SLOT_REQUEST";
export const POST_BOOK_SLOT_SUCCESS = "POST_BOOK_SLOT_SUCCESS";
export const POST_BOOK_SLOT_FAILURE = "POST_BOOK_SLOT_FAILURE";


export const GET_USER_BOOK_SLOT_REQUEST = "GET_USER_BOOK_SLOT_REQUEST";
export const GET_USER_BOOK_SLOT_SUCCESS = "GET_USER_BOOK_SLOT_SUCCESS";
export const GET_USER_BOOK_SLOT_FAILURE = "GET_USER_BOOK_SLOT_FAILURE";


export const GET_USER_BASED_ON_CENTER_REQUEST = "GET_USER_BASED_CENTER_REQUEST";
export const GET_USER_BASED_ON_CENTER_SUCCESS = "GET_USER_BASED_CENTER_SUCCESS";
export const GET_USER_BASED_ON_CENTER_FAILURE = "GET_USER_BASED_CENTER_FAILURE";


export const GET_USERS_BY_CENTER_REQUEST = 'GET_USERS_BY_CENTER_REQUEST';
export const GET_USERS_BY_CENTER_SUCCESS = 'GET_USERS_BY_CENTER_SUCCESS';
export const GET_USERS_BY_CENTER_FAILURE = 'GET_USERS_BY_CENTER_FAILURE';

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';


export const ACCEPT_USER_REQUEST = 'ACCEPT_USER_REQUEST';
export const ACCEPT_USER_SUCCESS = 'ACCEPT_USER_SUCCESS';
export const ACCEPT_USER_FAILURE = 'ACCEPT_USER_FAILURE';

export const REJECT_USER_REQUEST = 'REJECT_USER_REQUEST';
export const REJECT_USER_SUCCESS = 'REJECT_USER_SUCCESS';
export const REJECT_USER_FAILURE = 'REJECT_USER_FAILURE';
