export const GET_LOCATION_REQUEST = "GET_LOCATION_REQUEST";
export const GET_LOCATION_SUCCESS = "GET_LOCATION_SUCCESS";
export const GET_LOCATION_FAILURE = "GET_LOCATION_FAILURE";


export const POST_LOCATION_REQUEST = "POST_LOCATION_REQUEST";
export const POST_LOCATION_SUCCESS = "POST_LOCATION_SUCCESS";
export const POST_LOCATION_FAILURE = "POST_LOCATION_FAILURE";




export const POST_BOOK_SLOT_REQUEST = "POST_BOOK_SLOT_REQUEST";
export const POST_BOOK_SLOT_SUCCESS = "POST_BOOK_SLOT_SUCCESS";
export const POST_BOOK_SLOT_FAILURE = "POST_BOOK_SLOT_FAILURE";




export const GET_USER_BOOK_SLOT_REQUEST = "GET_USER_BOOK_SLOT_REQUEST";
export const GET_USER_BOOK_SLOT_SUCCESS = "GET_USER_BOOK_SLOT_SUCCESS";
export const GET_USER_BOOK_SLOT_FAILURE = "GET_USER_BOOK_SLOT_FAILURE";

